// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccfumesbuqjpxfuhupxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZnVtZXNidXFqcHhmdWh1cHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTAyMDQsImV4cCI6MjA3NTY2NjIwNH0.L8riBS38E4-gUUkAWCREW60463n6a-97LUUTX6aUqgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});